version: '2'

services:
  mysql:
    build: ./mysql
    volumes_from:
      - volumes_data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: docker_mysql
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
  volumes_data:
    image: tianon/true
    volumes:
      - ./shares:/shares
      - ./data/mysql:/var/lib/mysql
